#!/bin/bash

# Monthly Network Security Scan Script
# Scans your public IP for open ports and saves a markdown report.
#
# IMPORTANT: Only scan networks and IP addresses you own or are
# explicitly authorized to test. Unauthorized port scanning may be
# illegal in your jurisdiction.
#
# Usage:
#   ./scripts/monthly-security-scan.sh
#
# Configuration via environment variables (set before running, or export in your shell):
#   OBSIDIAN_VAULT   - where to write reports (default: ~/security-reports)
#
# Example:
#   OBSIDIAN_VAULT="$HOME/Documents/SecurityReports" ./scripts/monthly-security-scan.sh

# Configuration
OBSIDIAN_VAULT="${OBSIDIAN_VAULT:-$HOME/security-reports}"
mkdir -p "$OBSIDIAN_VAULT"

DATE=$(date +%Y-%m-%d)
REPORT_FILE="$OBSIDIAN_VAULT/$DATE Security Scan Report.md"

# Get current public IP
echo "Getting public IP address..."
PUBLIC_IP=$(curl -s https://api.ipify.org)

if [ -z "$PUBLIC_IP" ]; then
    echo "Error: Could not determine public IP"
    exit 1
fi

echo "Scanning IP: $PUBLIC_IP"

# Run nmap scan
echo "Running nmap scan (this may take 1-2 minutes)..."
SCAN_OUTPUT=$(nmap -Pn -sV -T4 --top-ports 100 $PUBLIC_IP 2>&1)

# Get hostname
HOSTNAME=$(echo "$SCAN_OUTPUT" | grep "Nmap scan report for" | sed 's/Nmap scan report for //')

# Count port states
OPEN_PORTS=$(echo "$SCAN_OUTPUT" | grep -c "^[0-9].*open")
FILTERED_PORTS=$(echo "$SCAN_OUTPUT" | grep -c "^[0-9].*filtered")
CLOSED_PORTS=$(echo "$SCAN_OUTPUT" | grep "Not shown:" | grep -oE '[0-9]+' | head -1)

# Determine security rating
if [ "$OPEN_PORTS" -eq 0 ]; then
    if [ "$FILTERED_PORTS" -gt 0 ]; then
        RATING="EXCELLENT ✅"
        SCORE="10/10"
    else
        RATING="GOOD ✅"
        SCORE="8/10"
    fi
elif [ "$OPEN_PORTS" -le 2 ]; then
    RATING="FAIR ⚠️"
    SCORE="6/10"
else
    RATING="POOR 🚨"
    SCORE="3/10"
fi

# Generate Markdown Report
cat > "$REPORT_FILE" << EOF
# Network Security Scan Report

**Date:** $(date +"%B %d, %Y at %I:%M %p")
**Target IP:** $PUBLIC_IP
**Hostname:** $HOSTNAME
**Security Rating:** $RATING ($SCORE)

---

## 🔍 Quick Summary

\`\`\`
Open Ports:     $OPEN_PORTS
Filtered Ports: $FILTERED_PORTS
Closed Ports:   ${CLOSED_PORTS:-94}
\`\`\`

---

## 📊 Detailed Scan Results

\`\`\`
$SCAN_OUTPUT
\`\`\`

---

## 🛡️ Security Analysis

### Port States Explained:
- **OPEN** 🔴 - Service is actively accepting connections (potential risk)
- **FILTERED** 🟡 - Firewall is blocking access (good for external scan)
- **CLOSED** 🟢 - No service listening (ideal state)

### Current Status:

EOF

# Add specific port analysis
echo "$SCAN_OUTPUT" | grep "^[0-9]" | while read -r line; do
    PORT=$(echo "$line" | awk '{print $1}')
    STATE=$(echo "$line" | awk '{print $2}')
    SERVICE=$(echo "$line" | awk '{print $3}')

    if [[ "$STATE" == "open" ]]; then
        ICON="🔴 CRITICAL"
        ACTION="Close this port immediately unless required"
    elif [[ "$STATE" == "filtered" ]]; then
        ICON="✅ Good"
        ACTION="Firewall is protecting this port"
    else
        ICON="✅ Good"
        ACTION="No service listening"
    fi

    echo "**Port $PORT ($SERVICE):** $STATE - $ICON" >> "$REPORT_FILE"
    echo "- *Action:* $ACTION" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
done

# Add recommendations
cat >> "$REPORT_FILE" << EOF

---

## 💡 Recommendations

EOF

if [ "$OPEN_PORTS" -eq 0 ]; then
    cat >> "$REPORT_FILE" << EOF
✅ **Excellent security posture!** No action required.

### Monthly Maintenance:
- Review this report for any changes from previous month
- Verify no new ports have been opened
- Keep firewall enabled
- Avoid unnecessary port forwarding

EOF
else
    cat >> "$REPORT_FILE" << EOF
⚠️ **Action Required:** You have $OPEN_PORTS open port(s).

### Immediate Actions:
1. Review each open port listed above
2. Close ports that are not needed
3. For required services, ensure:
   - Strong authentication is enabled
   - Software is up to date
   - Consider VPN access instead of direct exposure

EOF
fi

# Portable next-month date (works on macOS and Linux)
next_month=$(date -v+1m +"%B %d, %Y" 2>/dev/null || date -d "+1 month" +"%B %d, %Y")

# Add comparison section
cat >> "$REPORT_FILE" << EOF
---

## 📈 Historical Comparison

To track changes over time, compare with previous scans in this folder:

\`\`\`bash
# View all scan reports
ls -lt "$OBSIDIAN_VAULT/"
\`\`\`

---

## 🔗 Related Notes

- [[Network Security Best Practices]]
- [[MITRE ATT&CK Framework]]
- [[Security Monitoring]]

---

## 📝 Next Actions

- [ ] Review all detected ports
- [ ] Compare with last month's scan
- [ ] Update firewall rules if needed
- [ ] Document any changes in network configuration

---

*Automated scan generated by monthly-security-scan.sh*
*Next scan scheduled: $next_month*
EOF

echo ""
echo "✅ Scan complete!"
echo "📄 Report saved to: $REPORT_FILE"
echo ""
echo "Summary:"
echo "  IP Address:      $PUBLIC_IP"
echo "  Security Rating: $RATING"
echo "  Open Ports:      $OPEN_PORTS"
echo "  Filtered Ports:  $FILTERED_PORTS"
echo ""
